### ISSUE TITLE
Delete topic failed. 

### ISSUE THREAD

**Issue by tangshihui** [apache/pulsar-manager#296]
Response is 500, internal error. 
1: why request to url:  http://ip:9527/admin/v2/persistent/akka-test/default/batch1_topic
why the port is 9527, why not 8080?
2, Response: 
timestamp: "2020-04-27T12:55:37.483+0000"
status: 500
error: "Internal Server Error"
message: "Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)"

**Comment by tuteng** [comment]
You can refer to this architecture diagram https://github.com/apache/pulsar-manager#apache-pulsar-manager, 9527 is the front-end service port, 8080 is the pulsar cluster service port.

You can try to debug according to this process: https://github.com/apache/pulsar-manager/issues/214 @tangshihui

**Comment by tangshihui** [comment]
@tuteng I reviewed the pulsar-manager.log. There are so many error logs:
2020-04-28 02:05:00.537 ERROR 39 --- [pool-2-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.

org.springframework.jdbc.BadSqlGrammarException: 
### Error querying database.  Cause: org.postgresql.util.PSQLException: ERROR: LIMIT #,# syntax is not supported
  Hint: Use separate LIMIT and OFFSET clauses.
  Position: 38
### The error may exist in org/apache/pulsar/manager/mapper/EnvironmentsMapper.java (best guess)
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT name,broker FROM environments LIMIT ?, ?
### Cause: org.postgresql.util.PSQLException: ERROR: LIMIT #,# syntax is not supported
  Hint: Use separate LIMIT and OFFSET clauses.
  Position: 38
; bad SQL grammar []; nested exception is org.postgresql.util.PSQLException: ERROR: LIMIT #,# syntax is not supported
  Hint: Use separate LIMIT and OFFSET clauses.
  Position: 38
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:234) ~[spring-jdbc-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72) ~[spring-jdbc-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73) ~[mybatis-spring-1.3.2.jar:1.3.2]
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446) ~[mybatis-spring-1.3.2.jar:1.3.2]
	at com.sun.proxy.$Proxy132.selectList(Unknown Source) ~[na:na]

**Comment by tangshihui** [comment]
@tuteng  According to issue #214 , May be I had a wrong config:
/bin/pulsar-admin clusters get pulsar-cluster
{
  "serviceUrl" : "http://ip-1:8080",
  "brokerServiceUrl" : "pulsar://ip-1:6650,ip-2:6650,-ip-3:6650"
}
After update brokerServiceUrl to "pulsar://ip-1:6650", it works correctly.
Thanks !
