### ISSUE TITLE
java.net.MalformedURLException: For input string: "8080,IP2:8080,IP3:8080"

### ISSUE THREAD

**Issue by sakurafly123** [apache/pulsar-manager#325]
Hello
When you set the cluster's Http Service  URl like this format "http://ip:port,ip2:port,ip3:port", there are a exception.

java.net.MalformedURLException: For input string: "8080,ip:8080ip:8080"
	at java.net.URL.<init>(URL.java:627) ~[na:1.8.0_73]
	at java.net.URL.<init>(URL.java:490) ~[na:1.8.0_73]
	at java.net.URL.<init>(URL.java:439) ~[na:1.8.0_73]
	at org.apache.pulsar.manager.service.impl.PulsarAdminServiceImpl.getAuthHeader(PulsarAdminServiceImpl.java:110) ~[main/:na]
	at org.apache.pulsar.manager.zuul.EnvironmentForward.forwardRequest(EnvironmentForward.java:135) [main/:na]
	at org.apache.pulsar.manager.zuul.EnvironmentForward.run(EnvironmentForward.java:129) [main/:na]
	at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:117) [zuul-core-1.3.1.jar:1.3.1]

**Comment by jiazhai** [comment]
@sakurafly123 currently Pulsar manager is not supporting this feature.

**Comment by jiazhai** [comment]
If change to use Pulsar-admin-client, then pulsar manager could support this feature.
