### ISSUE TITLE
java.io.IOException: Cannot find any valid line inside file /data/app/dbdata/data/nodeid

### ISSUE THREAD

**Issue by bcxu** [apache/pulsar-manager#348]
When I run pulsar-manager ,the docker display the error:
2020-10-21 15:58:24.798  INFO 8 --- [ost-startStop-1] herddb.server.LocalNodeIdManager         : Looking for local node id into file /data/app/dbdata/data/nodeid
2020-10-21 15:58:24.807 ERROR 8 --- [ost-startStop-1] herddb.server.LocalNodeIdManager         : Error while reading file /data/app/dbdata/data/nodeid

java.io.IOException: Cannot find any valid line inside file /data/app/dbdata/data/nodeid
	at herddb.server.LocalNodeIdManager.readLocalNodeId(LocalNodeIdManager.java:64) ~[herddb-core-0.19.0.jar:na]
	at herddb.server.Server.<init>(Server.java:201) [herddb-core-0.19.0.jar:na]
	at herddb.jdbc.HerdDBEmbeddedDataSource.startEmbeddedServer(HerdDBEmbeddedDataSource.java:92) [herddb-jdbc-0.19.0.jar:na]
	at herddb.jdbc.HerdDBEmbeddedDataSource.ensureClient(HerdDBEmbeddedDataSource.java:71) [herddb-jdbc-0.19.0.jar:na]
	at herddb.jdbc.BasicHerdDBDataSource.ensureConnection(BasicHerdDBDataSource.java:230) [herddb-jdbc-0.19.0.jar:na]
	at herddb.jdbc.BasicHerdDBDataSource.getConnection(BasicHerdDBDataSource.java:252) [herddb-jdbc-0.19.0.jar:na]
	at herddb.jdbc.BasicHerdDBDataSource.getConnection(BasicHerdDBDataSource.java:243) [herddb-jdbc-0.19.0.jar:na]
	at herddb.jdbc.Driver.connect(Driver.java:133) [herddb-jdbc-0.19.0.jar:na]

**Comment by sijie** [comment]
@eolivelli Are you able to take a look at this issue? It seems to be related to HerdDB.

**Comment by eolivelli** [comment]
Sure.

**Comment by eolivelli** [comment]
What's the content of that file?
Was it mounted in a persistent volume?
Do you have data? Or is a fresh new installation?
