### ISSUE TITLE
Docs for 0.2.0 are broken since #456 was merged two days ago

### ISSUE THREAD

**Issue by bithavoc** [apache/pulsar-manager#472]
Docs are broken for 0.2.0 since https://github.com/apache/pulsar-manager/pull/456 was merged

> Initialize database and table structures using the [file](https://github.com/apache/pulsar-manager/blob/master/src/main/resources/META-INF/sql/postgresql-schema.sql).
Docs for 0.2.0 reference to master branch sql script which to remove the creation of the `roles` and `role_binding` tables, the documentation is
The documentation states:

But the schema was updated to no longer include `roles

\cc @tuteng @urfreespace

**Comment by bithavoc** [comment]
It's more than just those two tables:

```
; ]; ERROR: null value in column "bookie" of relation "environments" violates not-null constraint
  Detail: Failing row contains (local, http://broker:8080, null).; nested exception is org.postgresql.util.PSQLException: ERROR: null value in column "bookie" of relation "environments" violates not-null constraint
  Detail: Failing row contains (local, http://broker:8080, null).] with root cause

org.postgresql.util.PSQLException: ERROR: null value in column "bookie" of relation "environments" violates not-null constraint
  Detail: Failing row contains (local, http://broker:8080, null).
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440) ~[postgresql-42.2.5.jar:42.2.5]
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183) ~[postgresql-42.2.5.jar:42.2.5]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308) ~[postgresql-42.2.5.jar:42.2.5]
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441) ~[postgresql-42.2.5.jar:42.2.5]
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365) ~[postgresql-42.2.5.jar:42.2.5]
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143) ~[postgresql-42.2.5.jar:42.2.5]
        at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:132) ~[postgresql-42.2.5.jar:42.2.5]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[HikariCP-2.7.9.jar:na]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[HikariCP-2.7.9.jar:na]
        at sun.reflect.GeneratedMethodAccessor107.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
        at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59) ~[mybatis-3.5.4.jar:3.5.4]
        at com.sun.proxy.$Proxy197.execute(Unknown Source) ~[na:na]
```
