### ISSUE TITLE
Cannot find cluster mangement and npe error in v0.3.0

### ISSUE THREAD

**Issue by magicsilence** [apache/pulsar-manager#477]
hi team,
I meet some problems when using pulsar-manager.

The first is cannot find `cluster management` in my pulsar-manager (v0.3.0)  and the pulsar cluster's version is v2.9.3.

![image](https://user-images.githubusercontent.com/823374/182355261-bc0a4535-7af0-44f0-8028-324093790c37.png)

Second, pulsar-manager's backend serive always output exception log: 
`
java.lang.NullPointerException: null
        at org.apache.pulsar.manager.service.impl.BrokerStatsServiceImpl.scheduleCollectStats(BrokerStatsServiceImpl.java:124) ~[pulsar-manager.jar:na]
        at sun.reflect.GeneratedMethodAccessor108.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_342]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_342]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-5.0.6.RELEASE.jar:5.0.6.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.0.6.RELEASE.jar:5.0.6.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_342]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_342]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_342]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_342]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_342]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_342]
        at java.lang.Thread.run(Thread.java:750) [na:1.8.0_342]
`

How can i fix it ?

Thank you.

**Comment by haiboself** [comment]
Same issue， the only difference is I deploy 0.3.0 in docker。

**Comment by haiboself** [comment]
Finally, I solved the problem by installing the v0.3.0 version rather than v0.2.0.  
The install command is:
```
docker pull apachepulsar/pulsar-manager:v0.3.0
docker run -it \
    -p 9527:9527 -p 7750:7750 \
    -e SPRING_CONFIGURATION_FILE=/pulsar-manager/pulsar-manager/application.properties \
    --link pulsar-standalone \
    apachepulsar/pulsar-manager:v0.3.0
```

**Comment by Apurva007** [comment]
Same issue. Cannot find the "clusters" in the sidebar.

**Comment by dongzhonghua** [comment]
enter /management/clusters in the url can find cluster management，will this be fixed in the next version?
