### ISSUE TITLE
org.asynchttpclient.netty.channel.ChannelManager: IllegalReferenceCountException

### ISSUE THREAD

**Issue by bpereto** [apache/pulsar-manager#569]
```
2024-05-06 08:17:46.147  WARN 11 --- [tExecutor-3-466] io.netty.util.concurrent.DefaultPromise  : An exception was thrown by org.asynchttpclient.netty.channel.ChannelManager$$Lambda$1738/0x00007fe6b8b77718.operationComplete()

io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:74) ~[netty-all-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:138) ~[netty-all-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.AbstractReferenceCounted.release(AbstractReferenceCounted.java:76) ~[netty-all-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.release(ReferenceCountedOpenSslContext.java:717) ~[netty-handler-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:88) ~[netty-all-4.1.66.Final.jar:4.1.66.Final]
	at org.asynchttpclient.netty.ssl.DefaultSslEngineFactory.destroy(DefaultSslEngineFactory.java:79) ~[async-http-client-2.12.1.jar:na]
	at org.asynchttpclient.netty.channel.ChannelManager.lambda$doClose$0(ChannelManager.java:301) ~[async-http-client-2.12.1.jar:na]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[netty-all-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552) ~[netty-all-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[netty-all-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184) ~[netty-all-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.group.DefaultChannelGroupFuture.addListener(DefaultChannelGroupFuture.java:147) ~[netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.group.DefaultChannelGroupFuture.addListener(DefaultChannelGroupFuture.java:41) ~[netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at org.asynchttpclient.netty.channel.ChannelManager.doClose(ChannelManager.java:301) ~[async-http-client-2.12.1.jar:na]
	at org.asynchttpclient.netty.channel.ChannelManager.lambda$close$1(ChannelManager.java:308) ~[async-http-client-2.12.1.jar:na]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[netty-all-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552) ~[netty-all-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[netty-all-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) ~[netty-all-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605) ~[netty-all-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:96) ~[netty-all-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.concurrent.MultithreadEventExecutorGroup$1.operationComplete(MultithreadEventExecutorGroup.java:117) ~[netty-all-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[netty-all-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571) ~[netty-all-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550) ~[netty-all-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.concurrent.DefaultPromise.access$200(DefaultPromise.java:35) ~[netty-all-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:502) ~[netty-all-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.concurrent.GlobalEventExecutor$TaskRunner.run(GlobalEventExecutor.java:240) ~[netty-all-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.66.Final.jar:4.1.66.Final]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

**Comment by lhotari** [comment]
We should upgrade the Pulsar client version to 3.2.2 in pulsar-manager
